// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF-O2Yvc552if4YNON0LLlE0bNBrJAWRQ',
    appId: '1:831444977679:web:dd4e20bfe3fba091d07b7a',
    messagingSenderId: '831444977679',
    projectId: 'health-teen-cloud',
    authDomain: 'health-teen-cloud.firebaseapp.com',
    storageBucket: 'health-teen-cloud.firebasestorage.app',
    measurementId: 'G-SND8MDQP3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ56G-t-Y6xrmLr6dhtxTAnbiFVCbAWVU',
    appId: '1:831444977679:android:48830020b1cd19f1d07b7a',
    messagingSenderId: '831444977679',
    projectId: 'health-teen-cloud',
    storageBucket: 'health-teen-cloud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe7CKc3LvrlLSwwEbqvh0vh4AX2HSnLl0',
    appId: '1:831444977679:ios:d1e80d5dc589ecc0d07b7a',
    messagingSenderId: '831444977679',
    projectId: 'health-teen-cloud',
    storageBucket: 'health-teen-cloud.firebasestorage.app',
    iosBundleId: 'com.healthteen.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe7CKc3LvrlLSwwEbqvh0vh4AX2HSnLl0',
    appId: '1:831444977679:ios:d1e80d5dc589ecc0d07b7a',
    messagingSenderId: '831444977679',
    projectId: 'health-teen-cloud',
    storageBucket: 'health-teen-cloud.firebasestorage.app',
    iosBundleId: 'com.healthteen.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF-O2Yvc552if4YNON0LLlE0bNBrJAWRQ',
    appId: '1:831444977679:web:5c701f889652c4fad07b7a',
    messagingSenderId: '831444977679',
    projectId: 'health-teen-cloud',
    authDomain: 'health-teen-cloud.firebaseapp.com',
    storageBucket: 'health-teen-cloud.firebasestorage.app',
    measurementId: 'G-BKKTQBY95W',
  );

}