// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXvxPh41tpuP_A8gEzMSv2h4b9GR6jFzQ',
    appId: '1:685202357285:web:5776f7ae74e49d99bbd3cc',
    messagingSenderId: '685202357285',
    projectId: 'health-care-b5f05',
    authDomain: 'health-care-b5f05.firebaseapp.com',
    storageBucket: 'health-care-b5f05.firebasestorage.app',
    measurementId: 'G-QEVZEXG70B',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXvxPh41tpuP_A8gEzMSv2h4b9GR6jFzQ',
    appId: '1:685202357285:web:5776f7ae74e49d99bbd3cc',
    messagingSenderId: '685202357285',
    projectId: 'health-care-b5f05',
    authDomain: 'health-care-b5f05.firebaseapp.com',
    storageBucket: 'health-care-b5f05.firebasestorage.app',
    measurementId: 'G-QEVZEXG70B',
  );

}